### ISSUE TITLE
shared library libstdc++.so.6: I/O error

### ISSUE THREAD

**Issue by mdoary** [h0l0gram/omega2-checkHumidity#1]
root@Omega:~/checkHumidity# ./checkHumidity
Error loading shared library libstdc++.so.6: I/O error (needed by ./checkHumidity)
Error relocating ./checkHumidity: __gxx_personality_v0: symbol not found
Error relocating ./checkHumidity: __cxa_pure_virtual: symbol not found
Error relocating ./checkHumidity: _ZTVN10__cxxabiv117__class_type_infoE: symbol not found
Error relocating ./checkHumidity: _ZTVN10__cxxabiv120__si_class_type_infoE: symbol not found
Error relocating ./checkHumidity: _ZTVN10__cxxabiv121__vmi_class_type_infoE: symbol not found
Error relocating ./checkHumidity: __gxx_personality_v0: symbol not found

**Comment by h0l0gram** [comment]
Hi @mdoary
Can you confirm that your Omega2 has firmware **>=0.1.10 b160**? 
Please check and copy&paste it here.

To check the firmware version:
```
root@Omega-1234:~# oupgrade -c
> Device Firmware Version: 0.1.10 b160
> Checking latest version online...
> Repo Firmware Version: 0.1.10 b160
> Comparing version numbers
> Device firmware is up to date!
root@Omega-1234:~# 
```
To upgrade your Omega2 see https://docs.onion.io/omega2-docs/updating-the-omega.html

**Comment by ebostijancic** [comment]
Hi, I had the same problem, the reason was that my omega2 plus had an corrupt rootfs partition, you can check that by calling `dmesg` and you will see some error messages as soon as you run checkHumidity.

**Comment by mdoary** [comment]
Using username "root".
BusyBox v1.26.2 () built-in shell (ash)

   ____       _             ____
  / __ \___  (_)__  ___    / __ \__ _  ___ ___ ____ _
 / /_/ / _ \/ / _ \/ _ \  / /_/ /  ' \/ -_) _ `/ _ `/
 \____/_//_/_/\___/_//_/  \____/_/_/_/\__/\_, /\_,_/
 W H A T  W I L L  Y O U  I N V E N T ? /___/
 -----------------------------------------------------
   Ω-ware: 0.1.10 b160
 -----------------------------------------------------
root@Lanraider Omega:~# oupgrade -c
> Device Firmware Version: 0.1.10 b160
> Checking latest version online...
> Repo Firmware Version: 0.1.10 b160
> Comparing version numbers
> Device firmware is up to date!
root@Lanraider Omega:~#

**Comment by mdoary** [comment]
It seems my problem was the GPIO PIN i was using. Pin 11 worked but 9 did not.
