### ISSUE TITLE
Inaccurate output: conversion maybe?

### ISSUE THREAD

**Issue by tkeifer** [h0l0gram/omega2-checkHumidity#2]
I have this running on an Onion Omega2+ with the 0.1.10 b160 firmware.

I am getting an output of:
59.900002
26.200001

I have a handheld temp/humidity meter right next to it reading 77.4 and 40%

Thoughts?

**Comment by h0l0gram** [comment]
If I remember correctly, I received these values when the wiring was bad. Did you add a pull-up resistor as shown in the photo?
